### PR TITLE
Fix docker postgres

### LINKED ISSUE #44: Postgres not supported when using the container image (cannot import psycopg2)
As part of the work happening in spantaleev/matrix-docker-ansible-deploy#740, I was trying to migrate `matrix-registration` to Postgres for us.

When the Docker container image is used and the configuration specifies `db: postgresql://.....`, SQLAlchemy attempts to import `psycopg2`, which fails:

> ModuleNotFoundError: No module named 'psycopg2'

-----------

I've tried fixing this by modifying `Dockerfile`, so that it would install `py3-psycopg2` and found some strange things:

- `PYTHON_VERSION=3.7`, yet Alpine 3.11 is used, where the default Python 3 interpreter is `3.8.x`, so there is a mismatch. Installing `py3-psycopg` means the module gets installed to `/usr/local/lib/python3.8/site-packages`. The Python 3.7 interpreter this image uses actually looks for modules in `/usr/local/lib/python3.7/site-packages`. I guess this mismatch should be corrected anyway. And now that Alpine is on 3.12, you probably want to be on that..?

- perhaps `FROM docker.io/python:${PYTHON_VERSION}-alpine as builder` should be changed to something more specific (instead of letting it use some random Alpine version). Not sure where it currently points right now (perhaps to 3.12?)

- even with all of the above fixes, I still couldn't get `import psycopg2` to work in the container's Python 3 interpreter. I'm not sure what's going on..

### PR DESCRIPTION
**Pull request by ZerataX**
fixes #44 

I haven't tested this yet, but I hope it does what is described in the Issue
Also now on every release I publish a docker build will be published to 
- https://hub.docker.com/repository/docker/zeratax/matrix-registration
- https://github.com/ZerataX?tab=packages&repo_name=matrix-registration

I'm extremely new to docker, does this help? @spantaleev

### CODE REVIEW

**Comment by spantaleev** [comment]
```
docker run -it --rm \
--entrypoint=/bin/sh \
docker.io/zeratax/matrix-registration:v0.7.2.dev1 \
-c '/usr/local/bin/python3 -c "import psycopg2"'
```

Returns:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'psycopg2'
```

so I guess it's the same as before.

--------------

One workaround to this seems to be to avoid using `docker.io/python:XXXX-alpine` and just use pure `docker.io/alpine:XXX` with `python3` and `py3-psycopg2` installed inside.

I haven't really figured out exactly how `matrix-registration` building really works. It seems a little odd how it copies things around. I wonder if there's a much better way.

-----------

Thanks for working on this! It'd be really cool if you get this pipeline working, so that we can use official `matrix-registration` images instead of me having to build and push them myself ;)

**Comment by ZerataX** [comment]
hmm maybe this is actually pretty trivial, this seems to work for me:

**Comment by spantaleev** [comment]
From what I understand with `pip install /path[postgres]`, you're telling `pip` to install the "postgres" extras (`extras_require` stuff from `setup.py`). That is, it now installs `psycopg2-binary>=2.8.4`

Seems good! I've confirmed that this fix works! Thank you! :+1: 
Looking forward to a new image which contains this fix.

**Comment by ZerataX** [comment]
@spantaleev exactly!

okay 0.7.2 is published:

- https://github.com/ZerataX/matrix-registration/packages/539584
- https://hub.docker.com/r/zeratax/matrix-registration/tags

**Comment by spantaleev** [comment]
Thanks for this! :bow: 

[matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) now [uses your official images](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/69f71f48a660a104bd394309edae83026e75636c).

**Pull request merged**
