### PR TITLE
[WIP] API consistency

### LINKED ISSUE #16: use patch instead of put

### LINKED ISSUE #38: optional log registered ips
to allow homeserver admins to better moderate their instance it should optionally be possible to log the associated ips for every registration

### PR DESCRIPTION
**Pull request by ZerataX**
fixes #16 
fixes #38 

  - [x] PUT -> PATCH
  - [x] Rename Properties
     - [x] `valid` -> `active`
     - [x] `one_time` -> `max_usage` allows to make a token n times usable
     - [x] `ex_date` -> `expiration_date` ~~(also rename python variables?)~~
     - [x] add new property `disabled` to disable a token
  - [x] update mechanism for db ~~(maybe wait on #17)~~
  - [x] adjust tests

### CODE REVIEW

**Comment by ZerataX** [comment]
@williamkray I plan on merging this soon and since you seem to be the first person to make use of the API I wanted to know if this seems sensible and also allow you to make changes before I merge this.

This also changes the db scheme and introduces #38

so to migrate your db you can just run:
```
alembic upgrade head
```

I do recommend to backup your db anyways though, since this is my first time using alembic

**Comment by williamkray** [comment]
thanks for alerting me! i'll take a look at it this weekend. just looking at your notes, it might be beneficial to have some endpoint that returns the _version_ of matrix-registration, so that i could check for that and either return an error if the version is incompatible, or use the appropriate logic. either way, my bot will need to be updated :)

**Comment by ZerataX** [comment]
Yeah that makes sense. I added:
`/api/version`, which replies with `{"version":"1.0.0.dev0"}`

Also I put everything under the subdirectory `/api/`

**Comment by williamkray** [comment]
don't wait around for me to push these changes, i didn't get a chance this weekend and my day job is more important. i've just added a warning to my bot that it currently only works for v0.7.x, that's enough warning if you make any big changes. i'll keep my eyes on this project and try to update my bot as necessary. thanks again for reaching out!

**Comment by benkuly** [comment]
any progress on that?

**Comment by ZerataX** [comment]
@benkuly sorry for the extrem delay. I'll probably refactor these into two pull requests so i can push a pre release version. that said this version should work except for the new secret mechanism i tried to implement for a nixpkgs release

**Comment by ZerataX** [comment]
going to put the nixos specific stuff in a new pr

**Pull request closed without merging**
